In [1]:
pip install pandas

Collecting pandasNote: you may need to restart the kernel to use updated packages.

  Downloading pandas-2.2.2-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.1.0-cp312-cp312-win_amd64.whl.metadata (59 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\saro\onedrive\desktop\data_spark_guvi\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\saro\onedrive\desktop\data_spark_guvi\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-2.2.2-cp312-cp312-win_amd64.whl (11.5 MB)
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
    --------------------------------------- 0.3/11.5 MB ? eta -:--:--
   -- ------------------------------------- 0.8/11.5 MB 2.8 MB/s eta 0:00:04
   --- ------------------------------------ 1.0/11.5 MB 2.2 MB/s eta 0:00:05
   ----- ---------------------------------- 1.6/11.5 MB 1.9 MB/s eta 0:00:06
   ------ --------------------------------- 1.8/11.5 MB 2.1 MB/s eta 0:00:05
   ------- -------------------------------- 2.1/11.5 MB 1.8 MB/s eta 0:00:06
   -------- ------------------------------- 2.4/11.5 MB 1.8 MB/s eta 0:00:06
   --------- ------------------------------ 2.6/11.5 MB 1.7 MB/s eta 0:00:06
   ---------- ----------------------------- 2.9/11.5 MB 1.6 MB/s eta 0:00:06
   ---------- ----------------------------- 3.1/11.5 MB 1.6 MB/s eta 0:00:06
   ------------ --------------------------- 3.7/11.5 MB 1.6 MB/s eta 0:00:05
   ------------- -------------------------- 3.9/11.5 MB 1.6 MB/s eta 0:00:05
   -------------- ------------------------- 4.2/11.5 MB 1.6 MB/s eta 0:00:05
   --------------- ------------------------ 4.5/11.5 MB 1.6 MB/s eta 0:00:05
   ---------------- ----------------------- 4.7/11.5 MB 1.6 MB/s eta 0:00:05
   ------------------ --------------------- 5.2/11.5 MB 1.5 MB/s eta 0:00:05
   ------------------ --------------------- 5.2/11.5 MB 1.5 MB/s eta 0:00:05
   ------------------- -------------------- 5.5/11.5 MB 1.5 MB/s eta 0:00:05
   -------------------- ------------------- 5.8/11.5 MB 1.4 MB/s eta 0:00:05
   -------------------- ------------------- 5.8/11.5 MB 1.4 MB/s eta 0:00:05
   -------------------- ------------------- 6.0/11.5 MB 1.4 MB/s eta 0:00:04
   --------------------- ------------------ 6.3/11.5 MB 1.4 MB/s eta 0:00:04
   --------------------- ------------------ 6.3/11.5 MB 1.4 MB/s eta 0:00:04
   ---------------------- ----------------- 6.6/11.5 MB 1.3 MB/s eta 0:00:04
   ----------------------- ---------------- 6.8/11.5 MB 1.3 MB/s eta 0:00:04
   ------------------------ --------------- 7.1/11.5 MB 1.3 MB/s eta 0:00:04
   ------------------------ --------------- 7.1/11.5 MB 1.3 MB/s eta 0:00:04
   ------------------------ --------------- 7.1/11.5 MB 1.3 MB/s eta 0:00:04
   ------------------------- -------------- 7.3/11.5 MB 1.2 MB/s eta 0:00:04
   ------------------------- -------------- 7.3/11.5 MB 1.2 MB/s eta 0:00:04
   -------------------------- ------------- 7.6/11.5 MB 1.2 MB/s eta 0:00:04
   --------------------------- ------------ 7.9/11.5 MB 1.2 MB/s eta 0:00:04
   --------------------------- ------------ 7.9/11.5 MB 1.2 MB/s eta 0:00:04
   ---------------------------- ----------- 8.1/11.5 MB 1.1 MB/s eta 0:00:03
   ----------------------------- ---------- 8.4/11.5 MB 1.1 MB/s eta 0:00:03
   ----------------------------- ---------- 8.4/11.5 MB 1.1 MB/s eta 0:00:03
   ------------------------------ --------- 8.7/11.5 MB 1.1 MB/s eta 0:00:03
   ------------------------------ --------- 8.7/11.5 MB 1.1 MB/s eta 0:00:03
   ------------------------------- -------- 8.9/11.5 MB 1.1 MB/s eta 0:00:03
   ------------------------------- -------- 9.2/11.5 MB 1.1 MB/s eta 0:00:03
   -------------------------------- ------- 9.4/11.5 MB 1.1 MB/s eta 0:00:02
   --------------------------------- ------ 9.7/11.5 MB 1.1 MB/s eta 0:00:02
   --------------------------------- ------ 9.7/11.5 MB 1.1 MB/s eta 0:00:02
   ----------------------------------- ---- 10.2/11.5 MB 1.1 MB/s eta 0:00:02
   ------------------------------------ --- 10.5/11.5 MB 1.1 MB/s eta 0:00:01
   ------------------------------------- -- 10.7/11.5 MB 1.1 MB/s eta 0:00:01
   -------------------------------------- - 11.0/11.5 MB 1.1 MB/s eta 0:00:01
   -------------------------------------- - 11.0/11.5 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  11.3/11.5 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------- 11.5/11.5 MB 1.1 MB/s eta 0:00:00
Downloading numpy-2.1.0-cp312-cp312-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 1.5 MB/s eta 0:00:08
   -- ------------------------------------- 0.8/12.6 MB 1.2 MB/s eta 0:00:10
   --- ------------------------------------ 1.0/12.6 MB 1.2 MB/s eta 0:00:10
   ---- ----------------------------------- 1.3/12.6 MB 1.2 MB/s eta 0:00:10
   ----- ---------------------------------- 1.6/12.6 MB 1.1 MB/s eta 0:00:10
   ----- ---------------------------------- 1.6/12.6 MB 1.1 MB/s eta 0:00:10
   ----- ---------------------------------- 1.8/12.6 MB 1.1 MB/s eta 0:00:10
   ------ --------------------------------- 2.1/12.6 MB 1.1 MB/s eta 0:00:10
   ------- -------------------------------- 2.4/12.6 MB 1.1 MB/s eta 0:00:10
   ------- -------------------------------- 2.4/12.6 MB 1.1 MB/s eta 0:00:10
   -------- ------------------------------- 2.6/12.6 MB 1.0 MB/s eta 0:00:10
   --------- ------------------------------ 2.9/12.6 MB 1.0 MB/s eta 0:00:10
   --------- ------------------------------ 2.9/12.6 MB 1.0 MB/s eta 0:00:10
   ---------- ----------------------------- 3.1/12.6 MB 1.0 MB/s eta 0:00:10
   ----------- ---------------------------- 3.7/12.6 MB 1.1 MB/s eta 0:00:09
   ------------- -------------------------- 4.2/12.6 MB 1.2 MB/s eta 0:00:08
   -------------- ------------------------- 4.5/12.6 MB 1.2 MB/s eta 0:00:07
   --------------- ------------------------ 5.0/12.6 MB 1.2 MB/s eta 0:00:07
   ----------------- ---------------------- 5.5/12.6 MB 1.3 MB/s eta 0:00:06
   ------------------- -------------------- 6.0/12.6 MB 1.4 MB/s eta 0:00:05
   -------------------- ------------------- 6.6/12.6 MB 1.4 MB/s eta 0:00:05
   --------------------- ------------------ 6.8/12.6 MB 1.4 MB/s eta 0:00:05
   ---------------------- ----------------- 7.1/12.6 MB 1.4 MB/s eta 0:00:04
   ------------------------ --------------- 7.6/12.6 MB 1.5 MB/s eta 0:00:04
   ------------------------- -------------- 8.1/12.6 MB 1.5 MB/s eta 0:00:03
   -------------------------- ------------- 8.4/12.6 MB 1.5 MB/s eta 0:00:03
   --------------------------- ------------ 8.7/12.6 MB 1.5 MB/s eta 0:00:03
   ----------------------------- ---------- 9.2/12.6 MB 1.5 MB/s eta 0:00:03
   ------------------------------ --------- 9.4/12.6 MB 1.5 MB/s eta 0:00:03
   ------------------------------ --------- 9.7/12.6 MB 1.5 MB/s eta 0:00:02
   ------------------------------- -------- 10.0/12.6 MB 1.5 MB/s eta 0:00:02
   ------------------------------- -------- 10.0/12.6 MB 1.5 MB/s eta 0:00:02
   -------------------------------- ------- 10.2/12.6 MB 1.5 MB/s eta 0:00:02
   --------------------------------- ------ 10.5/12.6 MB 1.5 MB/s eta 0:00:02
   ---------------------------------- ----- 10.7/12.6 MB 1.4 MB/s eta 0:00:02
   ----------------------------------- ---- 11.3/12.6 MB 1.5 MB/s eta 0:00:01
   ----------------------------------- ---- 11.3/12.6 MB 1.5 MB/s eta 0:00:01
   ------------------------------------ --- 11.5/12.6 MB 1.4 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.6 MB 1.4 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.6 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 1.4 MB/s eta 0:00:00
Downloading pytz-2024.1-py2.py3-none-any.whl (505 kB)
Downloading tzdata-2024.1-py2.py3-none-any.whl (345 kB)
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-2.1.0 pandas-2.2.2 pytz-2024.1 tzdata-2024.1

In [2]:
import pandas as pd

In [3]:
df_customers = pd.read_csv("CSV files\Customers.csv" , encoding='ISO-8859-1')

<>:1: SyntaxWarning: invalid escape sequence '\C'
<>:1: SyntaxWarning: invalid escape sequence '\C'
C:\Users\Saro\AppData\Local\Temp\ipykernel_5144\3778972734.py:1: SyntaxWarning: invalid escape sequence '\C'
  df_customers = pd.read_csv("CSV files\Customers.csv" , encoding='ISO-8859-1')

In [4]:
df_customers.isnull().sum()

CustomerKey     0
Gender          0
Name            0
City            0
State Code     10
State           0
Zip Code        0
Country         0
Continent       0
Birthday        0
dtype: int64

In [6]:
df_customers["State Code"].fillna('Unknown', inplace=True)

C:\Users\Saro\AppData\Local\Temp\ipykernel_5144\46998460.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_customers["State Code"].fillna('Unknown', inplace=True)

In [7]:
df_customers

,CustomerKey,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday
0,301,Female,Lilly Harding,WANDEARAH EAST,SA,South Australia,5523,Australia,Australia,7/3/1939
1,325,Female,Madison Hull,MOUNT BUDD,WA,Western Australia,6522,Australia,Australia,9/27/1979
2,554,Female,Claire Ferres,WINJALLOK,VIC,Victoria,3380,Australia,Australia,5/26/1947
3,786,Male,Jai Poltpalingada,MIDDLE RIVER,SA,South Australia,5223,Australia,Australia,9/17/1957
4,1042,Male,Aidan Pankhurst,TAWONGA SOUTH,VIC,Victoria,3698,Australia,Australia,11/19/1965
...,...,...,...,...,...,...,...,...,...,...
15261,2099600,Female,Denisa Duková,Houston,TX,Texas,77017,United States,North America,3/25/1936
15262,2099618,Male,Justin Solórzano,Mclean,VA,Virginia,22101,United States,North America,2/16/1992
15263,2099758,Male,Svend Petrussen,Wilmington,NC,North Carolina,28405,United States,North America,11/9/1937
15264,2099862,Female,Lorenza Rush,Riverside,CA,California,92501,United States,North America,10/12/1937
15265,2099937,Male,Zygmunt Kaminski,Bloomfield Township,MI,Michigan,48302,United States,North America,8/18/1965